trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - 'asngsite/ui'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    pushd asngsite/ui && npm install && ng build --prod --output-path=asngsite/ui-prod && popd
  displayName: 'npm install and build'

- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(build.sourcesDirectory)/asngsite/ui-prod'
    azureSubscription: 'Microsoft Azure Personal Dev (a3b2c315-5cd1-4e2e-bad7-f671b6ce4410)'
    destination: azureBlob
    containerName: 'uofi-ui'
  displayName: 'Copy to BLOb storage'
